apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: test-web
  name: test-web
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: test-web
status:
  loadBalancer: {}
