apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: test-worker
  name: test-worker
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: test-worker
status:
  loadBalancer: {}
