apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: selenium
  name: selenium
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: selenium
status:
  loadBalancer: {}
