apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: selenium
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: selenium
    spec:
      containers:
      - image: selenium/standalone-firefox:2.53.1-beryllium
        name: selenium
        resources: {}
      restartPolicy: Always
status: {}
