apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: test-rabbitmq
  name: test-rabbitmq
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: test-rabbitmq
status:
  loadBalancer: {}
