apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: test-rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: test-rabbitmq
        resources: {}
      restartPolicy: Always
status: {}
